integration:
	go test -integration -v
	go test -testserver -v
	go test -integration -testserver -v
	go test -integration -optimized-allocator -v ./...
	go test -testserver -optimized-allocator -v ./...
	go test -integration -testserver -optimized-allocator -v ./...

integration_w_race:
	go test -race -integration -v
	go test -race -testserver -v
	go test -race -integration -testserver -v
	go test -race -integration -optimized-allocator -v ./...
	go test -race -testserver -optimized-allocator -v ./...
	go test -race -integration -optimized-allocator -testserver -v ./...


